version: '3.4'

services:
  app:
    container_name: plex-bot-app
    build: .
    image: phlak/plex-bot-dev:local
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: 'local'
      LOG_CHANNEL: 'stderr'
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-app}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    ports:
      - ${APP_PORT:-80}:80
    extra_hosts:
      - plex-bot.local:127.0.0.1
      - host.docker.internal:${DOCKER_HOST_IP:-172.17.0.1}
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}

  mysql:
    container_name: plex-bot-mysql
    image: mysql:8.0
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.docker/mysql/:/docker-entrypoint-initdb.d

  redis:
    container_name: plex-bot-redis
    image: redis:6.0
    ports:
      - ${REDIS_PORT:-6379}:6379

  horizon:
    container_name: plex-bot-horizon
    image: phlak/plex-bot-dev:local
    depends_on:
      - redis
    environment:
      APP_ENV: 'local'
      LOG_CHANNEL: 'stderr'
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    volumes:
      - ./:/var/www/html
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    command: php artisan horizon

volumes:
  mysql-data:
    driver: local
