services:

  app:
    build:
      context: .
      target: dev
    image: phlak/discord-bot:dev
    depends_on: [mysql, valkey]
    extra_hosts:
      - discord-bot.local:127.0.0.1
      - host.docker.internal:host-gateway
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.dev.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.dev.conf:/etc/apache2/sites-available/000-default.conf
    user: ${HOST_USER_ID:-1000}:${HOST_GROUP_ID:-1000}

  mysql:
    image: mysql:8.4
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.docker/mysql/:/docker-entrypoint-initdb.d

  valkey:
    image: valkey/valkey:9.0
    ports:
      - ${VALKEY_PORT:-6379}:6379

  horizon:
    image: phlak/discord-bot:dev
    depends_on: [valkey]
    profiles: [horizon]
    environment:
      APP_ENV: 'local'
      LOG_CHANNEL: 'stderr'
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'valkey'
      REDIS_PORT: 6379
    volumes:
      - ./:/var/www/html
    user: ${HOST_USER_ID:-1000}:${HOST_GROUP_ID:-1000}
    command: php artisan horizon

  artisan:
    image: phlak/discord-bot:dev
    entrypoint: php artisan
    depends_on: [mysql, valkey]
    profiles: [artisan]
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.dev.ini:/usr/local/etc/php/php.ini
    user: ${HOST_USER_ID:-1000}:${HOST_GROUP_ID:-1000}

volumes:
  mysql-data:
    driver: local