services:
  app:
    container_name: discord-bot-app
    build: .
    image: phlak/discord-bot:dev
    depends_on: [mysql, redis]
    ports:
      - ${APP_PORT:-80}:80
    extra_hosts:
      - discord-bot.local:127.0.0.1
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}

  mysql:
    container_name: discord-bot-mysql
    image: mysql:8.0
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.docker/mysql/:/docker-entrypoint-initdb.d

  redis:
    container_name: discord-bot-redis
    image: redis:6.0
    ports:
      - ${REDIS_PORT:-6379}:6379

  horizon:
    container_name: discord-bot-horizon
    image: phlak/discord-bot:dev
    depends_on: [redis]
    profiles: [horizon]
    environment:
      APP_ENV: 'local'
      LOG_CHANNEL: 'stderr'
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    volumes:
      - ./:/var/www/html
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    command: php artisan horizon

  artisan:
    container_name: discord-bot-artisan
    image: phlak/discord-bot:dev
    entrypoint: php artisan
    depends_on: [mysql, redis]
    profiles: [artisan]
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}

volumes:
  mysql-data:
    driver: local
